### ISSUE TITLE
Invalid role token not recognized

### ISSUE THREAD

**Issue by ulkoenig** [prabago/kong-plugin-jwt-auth-rbac#1]
Hi,

An invalid role token is not recognized. The problem is the return code at line 129 in the if statement.

_return false, {status = 401, message = "Bad token; " .. tostring(err)}_

should be replaced with

_return kong.response.exit(401, { message = "Bad token; " .. tostring(err)})_

Maybe you can fix it.
Thanks!

**Comment by prabagodelrio** [comment]
Done! Thx!
