### ISSUE TITLE
Multiple roles in a config.roles

### ISSUE THREAD

**Issue by ulkoenig** [prabago/kong-plugin-jwt-auth-rbac#2]
Hi,

In the setup of the plugin multiple roles in config.roles like [user, admin, uma_authorization] will not be recognized as an array. They are stored as a string in the first element of the config.roles array.

The output from a http://localhost:8001/plugins shows the config like this:

> "config": {
>                 "roles": [
>                     "user,admin,uma_authorization"
>                 ],]

As a workaround you can add a check before the roles will be check, e.g.

> --
  -- roles are all in the first element of a table. Seems to be a issue in the configuration part of the plugin
  -- This is a workaround
  --
  if  type(conf.roles) == "table" then
    -- in declarative db-less setup the roles can be separated by a space
    if string.find(conf.roles[1], " ") then
        conf_roles_table = split(conf.roles[1], " ")
    end
    if string.find(conf.roles[1], ",") then
        conf_roles_table = split(conf.roles[1], ",")
    end
    conf.roles = conf_roles_table
  end
  -- end of workaround

 

>  if conf.policy == policy_ANY and not role_in_roles_claim(conf.roles, roles) then

Maybe you can fix it.
Thanks!

**Comment by prabagodelrio** [comment]
Done Thx!
