### ISSUE TITLE
Base plugin depricated

### ISSUE THREAD

**Issue by shusriva** [prabago/kong-plugin-jwt-auth-rbac#4]
Hi @prabago ,

We are trying to utilize this plugins  but we are facing issue while enabling it in kong. 

Kong Version: kong:3.2.2-alpine

error we got:- 

```
stream logs failed container "ingress-controller" in pod "score-kong-kong-kong-596779d5b4-n22dr" is waiting to start: PodInitializing for core/score-kong-kong-kong-596779d5b4-n22dr (ingress-controller)
stream logs failed container "clear-stale-pid" in pod "score-kong-kong-kong-596779d5b4-n22dr" is waiting to start: PodInitializing for core/score-kong-kong-kong-596779d5b4-n22dr (clear-stale-pid)
stream logs failed container "proxy" in pod "score-kong-kong-kong-596779d5b4-n22dr" is waiting to start: PodInitializing for core/score-kong-kong-kong-596779d5b4-n22dr (proxy)
stream logs failed container "proxy" in pod "score-kong-kong-kong-596779d5b4-n22dr" is waiting to start: PodInitializing for core/score-kong-kong-kong-596779d5b4-n22dr (proxy)
stream logs failed container "ingress-controller" in pod "score-kong-kong-kong-596779d5b4-n22dr" is waiting to start: PodInitializing for core/score-kong-kong-kong-596779d5b4-n22dr (ingress-controller)
Stream closed EOF for core/score-kong-kong-kong-596779d5b4-n22dr (clear-stale-pid)
proxy     no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/base_plugin.lua'
proxy     no file '/usr/local/share/lua/5.1/kong/plugins/base_plugin.lua'
ingress-controller time="2023-04-28T11:09:02Z" level=info msg="getting the kubernetes client configuration" logger=setup
ingress-controller W0428 11:09:02.791480       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ingress-controller time="2023-04-28T11:09:02Z" level=info msg="starting standalone health check server" logger=setup
ingress-controller time="2023-04-28T11:09:02Z" level=info msg="getting the kong admin api client configuration" logger=setup
ingress-controller time="2023-04-28T11:09:02Z" level=info msg="Retrying kong admin api client call after error" error="making HTTP request: Get \"[https://localhost:8444/\":](https://localhost:8444//%22:) dial tcp [::1]:8444: connect: connection refused" logger=setup retries=0/60
ingress-controller time="2023-04-28T11:09:03Z" level=info msg="Retrying kong admin api client call after error" error="making HTTP request: Get \"[https://localhost:8444/\":](https://localhost:8444//%22:) dial tcp [::1]:8444: connect: connection refused" logger=setup retries=1/60
proxy     no file '/usr/local/share/lua/5.1/kong/plugins/base_plugin/init.lua'
proxy     no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/base_plugin.lua'
proxy     no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/base_plugin/init.lua'
proxy     no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/base_plugin.lua'
proxy     no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/base_plugin/init.lua'
proxy     no file '/usr/local/openresty/site/lualib/kong/plugins/base_plugin.so'
proxy     no file '/usr/local/openresty/lualib/kong/plugins/base_plugin.so'
proxy     no file './kong/plugins/base_plugin.so'
proxy     no file '/usr/local/lib/lua/5.1/kong/plugins/base_plugin.so'
proxy     no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/base_plugin.so'
proxy     no file '/usr/local/lib/lua/5.1/loadall.so'
proxy     no file '/home/kong/.luarocks/lib/lua/5.1/kong/plugins/base_plugin.so'
proxy     no file '/usr/local/openresty/site/lualib/kong.so'
proxy     no file '/usr/local/openresty/lualib/kong.so'
proxy     no file './kong.so'
proxy     no file '/usr/local/lib/lua/5.1/kong.so'
proxy     no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
proxy     no file '/usr/local/lib/lua/5.1/loadall.so'
proxy     no file '/home/kong/.luarocks/lib/lua/5.1/kong.so'
proxy stack traceback:
proxy     [C]: in function 'require'
proxy     ...cal/share/lua/5.1/kong/plugins/jwt-auth-rbac/handler.lua:1: in main chunk
proxy     [C]: at 0x7f3a1ac1b1c0
proxy     [C]: in function 'xpcall'
proxy     /usr/local/share/lua/5.1/kong/tools/utils.lua:691: in function 'load_module_if_exists'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
proxy     /usr/local/share/lua/5.1/kong/init.lua:622: in function 'init'
proxy     init_by_lua:3: in main chunk
proxy stack traceback:
proxy     [C]: in function 'error'
proxy     /usr/local/share/lua/5.1/kong/tools/utils.lua:700: in function 'load_module_if_exists'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
proxy     /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
proxy     /usr/local/share/lua/5.1/kong/init.lua:622: in function 'init'
proxy     init_by_lua:3: in main chunk
proxy nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:700: error loading module 'kong.plugins.jwt-auth-rbac.handler':
proxy ...cal/share/lua/5.1/kong/plugins/jwt-auth-rbac/handler.lua:1: module 'kong.plugins.base_plugin' not found:No LuaRocks module found for kong.plugins.base_plugin

```

It would be great if you can provide Dockerfile which enable this plugin on top of kong

**Comment by cnian94** [comment]
Hi @shusriva ,
check out the following links 
[https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#migrating-from-baseplugin-module](url)
[https://docs.konghq.com/gateway/latest/plugin-development/configuration/#describing-your-configuration-schema](url)

based on the information on official docs, I modified the schema.lua and handler.lua files like following:

//schema.lua

`local typedefs = require "kong.db.schema.typedefs"

return {
    name = "jwt-auth-rbac",
    fields = {{
        config = {
            type = "record",
            fields = {{
                roles = {
                    type = "array",
                    elements = {
                        type = "string"
                    }
                }
            }, {
                roles_claim_name = {
                    type = "string",
                    default = "roles"
                }
            }, {
                msg_error_any = {
                    type = "string",
                    default = "To be able to use this service you must have at least one of the roles configured"
                }
            }, {
                msg_error_all = {
                    type = "string",
                    default = "In order to use this service you must match all the roles configured with the associated ones in the JWT token"
                }
            }, {
                msg_error_not_roles_claimed = {
                    type = "string",
                    default = "The claim roles are not informed in the JWT token"
                }
            }, {
                policy = {
                    type = "string",
                    default = "any",
                    one_of = {"any", "all"}
                }
            }}
        }
    }},
    entity_checks = {{
        at_least_one_of = {"config.roles"}
    }}
}
`

//handler.lua

`--local BasePlugin = require "kong.plugins.base_plugin"

--local responses = require "kong.tools.responses"
local constants = require "kong.constants"
local jwt_decoder = require "kong.plugins.jwt.jwt_parser"
local responses = kong.response

local ngx_error = ngx.ERR
local ngx_debug = ngx.DEBUG
local ngx_log = ngx.log

local policy_ALL = 'all'
local policy_ANY = 'any'

local JWTAuthHandler = {
  VERSION  = "0.1.0",
  PRIORITY = 950,
}

--local JWTAuthHandler = BasePlugin:extend()


--JWTAuthHandler.PRIORITY = 950
--JWTAuthHandler.VERSION = "0.1.0"


--function JWTAuthHandler:new()
  --JWTAuthHandler.super.new(self, "jwt-auth")
--end`

I did not added the complete handler.lua file. I just added the commented lines and added lines. try and let me know if it is working for you.

**Comment by prabagodelrio** [comment]
Generate new release and tag v0.4.0 [Migrates the plugin according plugin development documentation]
